[theme]
base                     = "light"
primaryColor             = "#059669"
backgroundColor          = "#F0FDF4"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#111827"

[server]
headless = true
